### ISSUE TITLE
接口获取 “自动化测试工具” 板块数据出错

### ISSUE THREAD

**Issue by chenhengjie123** [testerhome/homeland#28]
请求：

```
GET https://testerhome.com/api/v3/topics.json?limit=73&node_id=2&offset=0&type=last_actived
```

返回 500 错误。

但把 limit 改为 72 则正常。

同步查看后台异常数据，发现以下异常信息：

```
#<NoMethodError: undefined method `read_attribute_for_serialization' for nil:NilClass>


/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model/serializer.rb:197:in `read_attribute_for_serialization'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model/serializer/field.rb:23:in `value'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model/serializer/attributes.rb:22:in `block in attributes'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model/serializer/attributes.rb:19:in `each'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model/serializer/attributes.rb:19:in `each_with_object'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model/serializer/attributes.rb:19:in `attributes'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model/serializer/caching.rb:216:in `fetch_attributes'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model/serializer.rb:169:in `serializable_hash'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model/serializer.rb:185:in `as_json'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:93:in `jsonify'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:89:in `block in jsonify'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:89:in `each'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:89:in `map'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:89:in `jsonify'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:91:in `block in jsonify'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:91:in `map'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:91:in `jsonify'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:89:in `block in jsonify'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:89:in `each'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:89:in `map'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:89:in `jsonify'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:33:in `encode'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:20:in `encode'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/object/json.rb:37:in `to_json'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/serializable_resource.rb:8:in `to_json'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:69:in `block (3 levels) in notify'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:22:in `block (3 levels) in instrument_rendering'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:79:in `block in notify_render'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:78:in `notify_render'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:21:in `block (2 levels) in instrument_rendering'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:95:in `block in tag_logger'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:95:in `tag_logger'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:20:in `block in instrument_rendering'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_render_callbacks'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:68:in `block (2 levels) in notify'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/renderers.rb:159:in `block in <module:Renderers>'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/action_controller/serialization.rb:53:in `block (2 levels) in <module:Serialization>'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/renderers.rb:152:in `block in _render_to_body_with_renderer'
/usr/local/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/lib/ruby/2.3.0/set.rb:306:in `each'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/renderers.rb:148:in `_render_to_body_with_renderer'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/renderers.rb:144:in `render_to_body'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/rendering.rb:26:in `render'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/rendering.rb:36:in `render'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
/var/www/homeland/app/controllers/api/v3/topics_controller.rb:46:in `index'
```

**Comment by lihuazhang** [comment]
数据问题，已经修复
