### ISSUE TITLE
sidekiq后台运行持续报错，没有正常运行

### ISSUE THREAD

**Issue by chenhengjie123** [testerhome/homeland#47]
2个体现：

# 1、后台看到的配置，和代码仓库不一致

仓库里的配置：
![image](https://user-images.githubusercontent.com/2800797/95087538-664e8000-0754-11eb-8fda-e8d48e8db12b.png)

后台查到的：
![image](https://user-images.githubusercontent.com/2800797/95087577-723a4200-0754-11eb-814f-bd9f2cdef2f8.png)

# 2、线上日志一直在报错：

```
$ docker logs homeland_worker -f
...
2020-10-05T13:30:48.524Z pid=1 tid=77h INFO: Cron Jobs - add job with name: spam_cleanup
W, [2020-10-05T13:30:48.641486 #1]  WARN -- : Creating scope :open. Overwriting existing method Topic.open.
2020-10-05T13:30:50.131Z pid=1 tid=77h INFO: Booted Rails 6.0.3.2 application in production environment
2020-10-05T13:30:50.131Z pid=1 tid=77h INFO: Running in ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
2020-10-05T13:30:50.131Z pid=1 tid=77h INFO: See LICENSE and the LGPL-3.0 for licensing details.
2020-10-05T13:30:50.131Z pid=1 tid=77h INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
Passing 'exists?' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.0/lib/sidekiq/launcher.rb:161:in `block (2 levels) in ❤')
Passing 'exists?' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.0/lib/sidekiq/launcher.rb:161:in `block (2 levels) in ❤')
...
```

**Comment by lanzhiheng** [comment]
@chenhengjie123 2并不是抱错，而是warning。

![image](https://user-images.githubusercontent.com/8858472/95886874-bdd29880-0db1-11eb-8146-e23fe2df64e7.png)
已经失败的会自动重试，sidekiq会做个记录。 如果是真的失败的会放在已停滞的那里。  https://www.youtube.com/watch?v=dGpbYqP5lr8&list=PLjeHh2LSCFrWGT5uVjUuFKAcrcj5kSai1&index=2 可以看看这个视频的详细介绍。
